import { useState } from 'react';
import type { Audit, Issue } from '@webguardian/shared';
import { AlertTriangle, Loader2, RefreshCw, Sparkles, Zap } from 'lucide-react';
import { api } from '../services/api';
import { SeverityBadge } from './Badges';

export function AiSummaryCard({ audit, issues, onOpen, onAuditChange }: { audit: Audit; issues: Issue[]; onOpen: (i: Issue) => void; onAuditChange: (a: Audit) => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const summary = audit.aiSummary;

  if (!summary) {
    return (
      <section className="card flex flex-col gap-3 p-5 sm:flex-row sm:items-center" aria-label="AI summary">
        <AlertTriangle className="h-5 w-5 shrink-0 text-sev-medium" aria-hidden="true" />
        <div className="flex-1">
          <p className="font-semibold">AI explanation temporarily unavailable</p>
          <p className="text-sm text-fg-muted">
            {audit.aiError ?? 'Gemini could not be reached.'} Every finding below is still backed by deterministic evidence.
          </p>
          {error && <p className="mt-1 text-sm text-sev-critical">{error}</p>}
        </div>
        <button
          type="button"
          className="btn-secondary"
          disabled={busy}
          onClick={async () => {
            setBusy(true);
            setError(null);
            try {
              onAuditChange(await api.retryAi(audit.id));
            } catch (e) {
              setError((e as Error).message);
            } finally {
              setBusy(false);
            }
          }}
        >
          {busy ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" /> : <RefreshCw className="h-4 w-4" aria-hidden="true" />}
          Retry Gemini
        </button>
      </section>
    );
  }

  return (
    <section aria-labelledby="ai-summary-h" className="card relative overflow-hidden">
      <div className="glow absolute inset-0 opacity-60" aria-hidden="true" />
      <div className="relative grid gap-6 p-6 lg:grid-cols-[1.2fr_1fr]">
        <div>
          <p className="flex items-center gap-2 text-xs font-semibold tracking-wider text-azure-400">
            <Sparkles className="h-4 w-4" aria-hidden="true" /> GEMINI ANALYSIS
          </p>
          <h2 id="ai-summary-h" className="mt-2 text-lg font-bold">
            Summary
          </h2>
          <p className="mt-2 leading-relaxed text-fg-muted">{summary.summary}</p>
          {summary.quickWins.length > 0 && (
            <div className="mt-4">
              <p className="flex items-center gap-1.5 text-xs font-semibold tracking-wider text-fg-subtle">
                <Zap className="h-3.5 w-3.5 text-sev-medium" aria-hidden="true" /> QUICK WINS
              </p>
              <ul className="mt-1.5 list-disc space-y-1 pl-5 text-sm text-fg-muted">
                {summary.quickWins.map((w) => (
                  <li key={w}>{w}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
        <div>
          <h3 className="text-xs font-semibold tracking-wider text-fg-subtle">FIX THESE FIRST</h3>
          <ol className="mt-2 space-y-2">
            {summary.topPriorities.map((p, idx) => {
              const issue = issues.find((i) => i.id === p.issueId);
              if (!issue) return null;
              return (
                <li key={p.issueId}>
                  <button type="button" onClick={() => onOpen(issue)} className="card card-hover flex w-full gap-3 p-3 text-left">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-xs font-bold text-brand-300">{idx + 1}</span>
                    <span className="min-w-0 space-y-1">
                      <span className="flex flex-wrap items-center gap-2">
                        <SeverityBadge severity={issue.severity} />
                        <span className="font-mono text-xs text-fg-subtle">#{issue.number}</span>
                      </span>
                      <span className="block text-sm font-semibold">{issue.title}</span>
                      <span className="block text-xs text-fg-muted">{p.reason}</span>
                    </span>
                  </button>
                </li>
              );
            })}
          </ol>
          <p className="mt-2 text-[11px] text-fg-subtle">
            Generated by {summary.model} from this audit's evidence only.
          </p>
        </div>
      </div>
    </section>
  );
}
